backend/posts/urls.py
from django.urls import path
from .views import PostListView

app_name = 'posts'

urlpatterns = [
    path(
        '',
        PostListView.as_view(),
        name='list'
    ),
]

backend/users/urls.py
from django.urls import path
from .views import (
    UserCreateView, UserLoginView, UserLogoutView, UserListView,
    UserUpdateView, UserPasswordChangeView
)

app_name = 'users'

urlpatterns = [
    path(
        'registration/',
        UserCreateView.as_view(),
        name='registration',
    ),
    path(
        'login/',
        UserLoginView.as_view(),
        name='login',
    ),
    path(
        'logout/',
        UserLogoutView.as_view(),
        name='logout',
    ),
    path(
        'settings/',
        UserUpdateView.as_view(),
        name='settings',
    ),
    path(
        'password_change/',
        UserPasswordChangeView.as_view(),
        name='password_change',
    ),
    path(
        '<slug:username>/',
        UserListView.as_view(),
        name='profile',
    ),
]

backend/weblog/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('posts.urls')),
    path('auth/', include('users.urls')),
    path('admin/', admin.site.urls),
]

backend/templates/includes/header.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <ul class="navbar-nav mr-auto mb-2 mb-lg-0">
      <span class="navbar-text">WeBlog</span>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'posts:list' %}">Посты</a>
      </li>
    </ul>
    <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
      {% if user.is_authenticated %}
        <a class="nav-link" href="{% url 'users:profile' request.user %}">
          {{ user.username}}
        </a>
        {% if user.is_staff %}
          <a class="nav-link" href="{% url 'admin:index' %}">Админ-зона</a>
        {% endif %}
        <a class="nav-link" href="{% url 'users:logout' %}">Выход</a>
      {% else %}
        <a class="nav-link" href="{% url 'users:login' %}">Вход</a>
        <a class="nav-link" href="{% url 'users:registration' %}">Регистрация</a>
      {% endif %}
    </ul>
  </div>
</nav>