backend/posts/urls.py
from django.urls import path
from .views import PostListView

app_name = 'posts'

urlpatterns = [
    path(
        '',
        PostListView.as_view(),
        name='list'
    ),
]

backend/users/urls.py
from django.urls import path
from .views import (
    UserCreateView, UserLoginView, UserLogoutView, UserListView,
    UserUpdateView, UserPasswordChangeView
)

app_name = 'users'

urlpatterns = [
    path(
        'registration/',
        UserCreateView.as_view(),
        name='registration',
    ),
    path(
        'login/',
        UserLoginView.as_view(),
        name='login',
    ),
    path(
        'logout/',
        UserLogoutView.as_view(),
        name='logout',
    ),
    path(
        'settings/',
        UserUpdateView.as_view(),
        name='settings',
    ),
    path(
        'password_change/',
        UserPasswordChangeView.as_view(),
        name='password_change',
    ),
    path(
        '<slug:username>/',
        UserListView.as_view(),
        name='profile',
    ),
]

backend/weblog/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('posts.urls')),
    path('auth/', include('users.urls')),
    path('admin/', admin.site.urls),
]

backend/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

from core.models import BlockModel


class WeBlogUser(BlockModel, AbstractUser):
    """Модель пользователя."""
    image = models.ImageField(
        'изображение',
        upload_to='images/',
        blank=True,
        null=True,
    )
    email = models.EmailField(
        'адрес электронной почты',
        unique=True,
        blank=False,
    )

    class Meta:
        constraints = [
            models.UniqueConstraint(
                fields=['username', 'email'],
                name='unique_user'
            )
        ]
        verbose_name = 'пользователь'
        verbose_name_plural = 'Пользователи'

    def __str__(self) -> str:
        return self.username


class Follow(models.Model):
    """Модель подписок."""
    user = models.ForeignKey(
        WeBlogUser,
        on_delete=models.CASCADE,
        related_name='follow_user',
        verbose_name='кто подписан',
    )
    following = models.ForeignKey(
        WeBlogUser,
        on_delete=models.CASCADE,
        related_name='follow_following',
        verbose_name='на кого подписан',
    )

    class Meta:
        verbose_name = 'подписка'
        verbose_name_plural = 'Подписки'

    def __str__(self) -> str:
        return (
            f'{self.user.username} подписан на {self.following.username}'
        )

backend/users/forms.py
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm, PasswordChangeForm
from django.contrib.auth import get_user_model
from django import forms

from core.forms import BootstrapFormMixin

User = get_user_model()


class WeBlogUserCreationForm(BootstrapFormMixin, UserCreationForm):
    """Форма регистрации пользователя."""

    class Meta(UserCreationForm.Meta):
        model = User
        fields = (
            'username',
            'email',
        )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['username'].widget.attrs.update({
                'placeholder': 'Имя пользовятеля',
            })
        self.fields['email'].widget.attrs.update({
                'placeholder': 'Почта',
            })
        self.fields['password1'].widget.attrs.update({
                'placeholder': 'Пароль',
            })
        self.fields['password2'].widget.attrs.update({
                'placeholder': 'Подтверждение пароля',
            })


class WeBlogAuthenticationForm(BootstrapFormMixin, AuthenticationForm):
    """Форма aутентификации пользователя."""
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['username'].widget.attrs.update({
                'placeholder': 'Имя пользовятеля',
            })
        self.fields['password'].widget.attrs.update({
                'placeholder': 'Пароль',
            })


class UserForm(BootstrapFormMixin, forms.ModelForm):
    """Форма настройки пользователя."""
    class Meta:
        model = User
        fields = (
            'image',
            'username',
            'first_name',
            'last_name',
            'email',
        )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs.update({
                'class': 'form-control mb-3',
            })


class UserPasswordChangeForm(BootstrapFormMixin, PasswordChangeForm):
    """Форма смены пароля."""

backend/users/views.py
from django.shortcuts import get_object_or_404
from django.views.generic import CreateView, ListView, UpdateView
from django.contrib.auth import get_user_model
from django.contrib.auth.views import LoginView, LogoutView, PasswordChangeView
from django.urls import reverse, reverse_lazy
from .forms import WeBlogUserCreationForm, WeBlogAuthenticationForm, UserForm, UserPasswordChangeForm

from core import constants

User = get_user_model()


class UserCreateView(CreateView):
    """Регистарция пользователя."""
    template_name = 'registration/registration_form.html'
    form_class = WeBlogUserCreationForm
    success_url = reverse_lazy('posts:list')


class UserLoginView(LoginView):
    """Вход в систему пользователя."""
    form_class = WeBlogAuthenticationForm


class UserLogoutView(LogoutView):
    """Выход из системы пользователя."""
    success_url = reverse_lazy('posts:list')


class UserListView(ListView):
    """Страница пользователя."""
    model = User
    template_name = 'users/user.html'
    paginate_by = constants.OBJECTS_PER_PAGE
    slug_url_kwarg = 'username'

    def get_queryset(self):
        self.author = get_object_or_404(User, username=self.kwargs['username'])
        return super().get_queryset()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['profile'] = self.author
        return context


class UserUpdateView(UpdateView):
    """Страница настройки пользователя."""
    model = User
    template_name = 'users/settings.html'
    form_class = UserForm

    def get_object(self):
        return self.request.user

    def get_success_url(self) -> str:
        return reverse(
            'users:profile',
            kwargs={'username': self.request.user.username}
        )


class UserPasswordChangeView(PasswordChangeView):
    """Страница смены пароля."""
    form_class = UserPasswordChangeForm
    success_url = reverse_lazy('users:settings')

backend/templates/users/settings.html
{% extends "base.html" %}
{% load static %}
{% block title %}
  Настройки
{% endblock title %}
{% block content %}
<div class="container mt-5">
  <div class="row justify-content-center">
    <div class="text-center mb-5">
      {% if user.image %}
        <img src="user.image.url" class="img-thumbnail" width="200" height="200">
      {% else %}
        <img src="{% static 'svg/person.svg' %}" class="img-thumbnail" width="200" height="200">
      {% endif %}
    </div>
    <div class="card col-5">
      <div class="card-body">
        <form method="post" enctype="multipart/form-data">
          {% csrf_token %}
          <div class="form-text flex-nowrap mb-1">
            {{ form.image.label }}
          </div>
          <div class="form-text text-danger flex-nowrap mb-1">
            {{ form.image.errors }}
          </div>
          {{ form.image }}
          <div class="form-text flex-nowrap mb-1">
            {{ form.username.label }}
          </div>
          <div class="form-text text-danger flex-nowrap mb-1">
            {{ form.username.errors }}
          </div>
          {{ form.username }}
          <div class="row flex-nowrap">
            <div class="col">
              <div class="form-text flex-nowrap mb-1">
                {{ form.first_name.label }}
              </div>
              <div class="form-text text-danger flex-nowrap mb-1">
                {{ form.first_name.errors }}
              </div>
              {{ form.first_name }}
            </div>
            <div class="col">
              <div class="form-text flex-nowrap mb-1">
                {{ form.last_name.label }}
              </div>
              <div class="form-text text-danger flex-nowrap mb-1">
                {{ form.last_name.errors }}
              </div>
              {{ form.last_name }}
            </div>
          </div>
          <div class="form-text flex-nowrap mb-1">
            {{ form.email.label }}
          </div>
          <div class="form-text text-danger flex-nowrap mb-1">
            {{ form.email.errors }}
          </div>
          {{ form.email }}
          <div class="form-text text-danger flex-nowrap mb-1">
            {{ form.non_field_errors }}
          </div>
          <a href="{% url 'users:password_change' %}" class="btn btn-outline-secondary mb-3">
            Изменить пароль
          </a>
          <br>
          <button type="submit" class="btn btn-secondary btn-lg btn-block">
            Сохранить изменения
          </button>
        </form>
      </div>
    </div>
  </div>
</div>
{% endblock content %}

backend/templates/users/user.html
{% extends "base.html" %}
{% load static %}
{% block title %}
  Профиль {{ profile.username }}
{% endblock title %}
{% block content %}
  {% if profile.image %}
    <img href="{{ profile.image }}">
  {% endif %}
  {% if request.user == profile %}
    <a href="{% url 'users:settings' %}">Настройки</a>
  {% endif %}
{% endblock content %}